"""A small SystemVerilog object model and the top-level netlist builder.

Nothing here generates arithmetic. Every compute unit is a hand-written module
in hardware/rtl; this stage only chooses parameters and wires instances
together, which is why the generated file stays readable and the timing
behaviour stays predictable.
"""


class SvSignal:
    def __init__(self, name, width=1):
        self.name = name
        self.width = int(width)

    def declaration(self):
        if self.width <= 1:
            return "logic %s;" % self.name
        return "logic [%d:0] %s;" % (self.width - 1, self.name)


class SvPort:
    def __init__(self, direction, name, width=1):
        self.direction = direction
        self.name = name
        self.width = int(width)

    def render(self):
        span = "" if self.width <= 1 else "[%d:0] " % (self.width - 1)
        keyword = "input  wire " if self.direction == "input" else "output logic "
        return "%s%s%s" % (keyword, span, self.name)


class SvInstance:
    def __init__(self, module, name, params=None, connections=None):
        self.module = module
        self.name = name
        self.params = dict(params or {})
        self.connections = dict(connections or {})

    def render(self, indent="    "):
        lines = []
        if self.params:
            lines.append("%s%s #(" % (indent, self.module))
            body = ["%s    .%s(%s)" % (indent, key, self._literal(value))
                    for key, value in self.params.items()]
            lines.append(",\n".join(body))
            lines.append("%s) %s (" % (indent, self.name))
        else:
            lines.append("%s%s %s (" % (indent, self.module, self.name))
        body = ["%s    .%s(%s)" % (indent, port, net)
                for port, net in self.connections.items()]
        lines.append(",\n".join(body))
        lines.append("%s);" % indent)
        return "\n".join(lines)

    @staticmethod
    def _literal(value):
        if isinstance(value, str):
            return '"%s"' % value
        if isinstance(value, bool):
            return "1'b1" if value else "1'b0"
        return str(int(value))


class SvModule:
    def __init__(self, name):
        self.name = name
        self.ports = []
        self.signals = []
        self.instances = []
        self.header_comment = ""

    def add_port(self, port):
        self.ports.append(port)
        return port

    def add_signal(self, signal):
        self.signals.append(signal)
        return signal

    def add_instance(self, instance):
        self.instances.append(instance)
        return instance

    def render(self):
        lines = []
        if self.header_comment:
            lines.extend("// " + line for line in self.header_comment.splitlines())
        lines.append("`default_nettype none")
        lines.append("")
        lines.append("module %s (" % self.name)
        lines.append(",\n".join("    " + p.render() for p in self.ports))
        lines.append(");")
        for signal in self.signals:
            lines.append("    " + signal.declaration())
        lines.append("")
        for instance in self.instances:
            lines.append(instance.render())
            lines.append("")
        lines.append("endmodule")
        lines.append("")
        lines.append("`default_nettype wire")
        return "\n".join(lines) + "\n"


class NetNames:
    """Maps a tensor to the three wires that carry its stream."""

    def __init__(self, graph):
        self.graph = graph
        self._alias = {}
        for name in graph.inputs:
            self._alias[name] = "s"
        for name in graph.outputs:
            self._alias[name] = "m"

    def prefix(self, tensor_name):
        return self._alias.get(tensor_name, tensor_name)

    def data(self, tensor_name):
        return "%s_tdata" % self.prefix(tensor_name)

    def valid(self, tensor_name):
        return "%s_tvalid" % self.prefix(tensor_name)

    def ready(self, tensor_name):
        return "%s_tready" % self.prefix(tensor_name)

    def is_boundary(self, tensor_name):
        return tensor_name in self._alias


class NetlistBuilder:
    """Turns a scheduled hardware graph into one top-level SystemVerilog module."""

    def __init__(self, graph, name="otf_top"):
        self.graph = graph
        self.name = name

    def build(self):
        graph, module = self.graph, SvModule(self.name)
        nets = NetNames(graph)
        module.header_comment = (
            "Generated by onnx2fpga. Streaming dataflow, one unit per layer.\n"
            "Compute lives in the hand-written modules under hardware/rtl.")

        in_name, out_name = graph.inputs[0], graph.outputs[0]
        module.add_port(SvPort("input", "clk"))
        module.add_port(SvPort("input", "rst_n"))
        module.add_port(SvPort("input", "s_tdata", self._width(in_name)))
        module.add_port(SvPort("input", "s_tvalid"))
        module.add_port(SvPort("output", "s_tready"))
        module.add_port(SvPort("output", "m_tdata", self._width(out_name)))
        module.add_port(SvPort("output", "m_tvalid"))
        module.add_port(SvPort("input", "m_tready"))

        for node in graph.topological_order():
            for name in node.outputs:
                if nets.is_boundary(name):
                    continue
                module.add_signal(SvSignal(nets.data(name), self._width(name)))
                module.add_signal(SvSignal(nets.valid(name)))
                module.add_signal(SvSignal(nets.ready(name)))

        for node in graph.topological_order():
            module.add_instance(SvInstance(
                node.module, "u_" + self._identifier(node.name),
                node.sv_params(graph), node.sv_connections(graph, nets)))
        return module

    def _width(self, tensor_name):
        tensor = self.graph.tensor(tensor_name)
        return tensor.elems_per_beat * tensor.dtype.bits

    @staticmethod
    def _identifier(name):
        return "".join(c if c.isalnum() or c == "_" else "_" for c in name)
